# _config.yml

# required, replace with your own information -----
title: Welcome to my page
author: Subham Das
description: > 
  A minimalist template for designing a personal GitHub Pages website - without typing a single line of code.
baseurl: "https://cryptosubh.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

